services:
  - docker

env:
  global:
    - secure: HgvkNlaR1pcnZcRscIM4eRi07uFogwbyVcrWrPG/0u5P1kpAYmrd7QfxcleqF5xZj+iAVdvCG0nbYGYkzAnXQIg0WBTC/FYtn9v1UrOJm7lLrspvBQkMSrxFUZFUJv3yXRHUgSKP1rLPaA0MzF8d/bRZolu83dgPWwhOZA+xuXA9FFd/qt8XZAI4ISolv1hyIW+K3VoP1f0nPuZb+zBQP/XGNE8HZHCdLlQrBTSQF8aSV0zt6IJsUNhsAFi6BMNxtutN0u18yIJrTTjBBh0cBau0wFoOtXr49h9sXrM+GL2F7wjQyszp7sBxmxwwJR4e+Z+LfKCI0WekivVBqZ4MeyYkdXeRbh1KNgURUutpIg7JM/WrOeuD1PvLkZTT0UoAICDOPopBNyNja3f+bIFvc1dfGTfuxc6KPZh4cl1bq841QFRv/iQpfTtgFjbqJbDVJS3U1V+pykiyu1YJcoEHpVhAH92d3aYQQlrf02zvBYmK+hXwtvUlOqz4QsAOFAupZSPCypWfdUcAsNRVVqZcRoHGAN+H5wjFZzGcL+bsJYGQ3UPSsPqBrMyFfleJGBNcaxcoxOuy/yPwY01rUYbQzl3w+IsTOrxHi9KvDre7Val4Fzmt29zPJS+yGveXrDSA+T6E8oxSQOxi0Ec7Kf4U3PAKNeEAE21GmdlBvXwspro=

before_install:
  - docker build -t nebulo:client-desktop .
  - docker run --name nebulo_client_desktop -e COVERALLS_TOKEN=$COVERALLS_TOKEN -d -v ${TRAVIS_BUILD_DIR}:/go/src/github.com/krostar/nebulo-client-desktop nebulo:client-desktop tail -f /dev/null

install:
  - docker exec nebulo_client_desktop make clean
  - docker exec nebulo_client_desktop make vendor

script:
  - docker exec nebulo_client_desktop make test CI=1
  - docker exec nebulo_client_desktop make coverage
  - docker exec nebulo_client_desktop retool do goveralls -coverprofile=coverage/coverage.out -service=travis-ci
